name: "Coffe Setup"

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:     
      - uses: GitLabBR/cupypi@v3
        with:
          username: caique9014
          password: ${{ secrets.TEST_PYPI_API_PASSWORD }}
        env:
          PASSWORD:  ${{ secrets.TEST_PYPI_API_PASSWORD }}
        
        
