name: "Coffe Setup"

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@v4.2.2
      - name: Cupypi Publish Python        
        uses: GitLabBR/cupypi@v1.1
        with:
          password: "${{ secrets.PYPI_API_TOKEN }}"
        
        
