name: "Coffe Setup"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:     
      - uses: GitLabBR/cupypi@v1.7
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        
        
