name: "Coffe Setup"

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@v4.2.2
      - name: Cupypi Publish Python        
        env:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        uses: GitLabBR/cupypi@v1,4
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        
        
