name: "Coffe Setup"

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pip
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            @actions/core
            @actions/github
      - name: Publish package
        uses: GitLabBR/cupypi@v1.0
        with:
          password: "${{ secrets.PYPI_API_TOKEN }}"
