name: "Coffe Setup"

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:     
      - uses: GitLabBR/cupypi@v2.7
        with:
          token: ${{ secrets.TEST_PYPI_API_TOKEN }}
          password: ${{ secrets.TEST_PYPI_API_PASSWORD }}
        
        
