name: "Coffe Setup"

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:     
      - uses: GitLabBR/cupypi@v4.1
        with:
          username: ${{ secrets.PYPI_API_USERNAME }}
          password: ${{ secrets.PYPI_API_PASSWORD }}
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.PYPI_API_USERNAME }}
        
        
