name: "Coffe Setup"

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cupypi Publish Python        
        uses: GitLabBR/cupypi@v1.0
        with:
          password: "${{ secrets.PYPI_API_TOKEN }}"
        
        
