name: "Coffe Setup"

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pip
        uses: actions/setup-python@v3
      - name: Run pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install @actions/core
          python -m pip install @actions/github
        
      - name: Publish package
        uses: GitLabBR/cupypi@v1.0
        with:
          password: "${{ secrets.PYPI_API_TOKEN }}"
