name: "Coffe Setup"

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm install @actions/core
          npm install @actions/github
      - name: Publish package
        uses: GitLabBR/cupypi@v1.0
        with:
          password: "${{ secrets.PYPI_API_TOKEN }}"
        
        
