name: "Coffe Setup"

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:     
      - uses: GitLabBR/cupypi@v2.1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        
        
